### ISSUE TITLE
[BUG] Exception raised in TailClark calculation

### ISSUE THREAD

**Issue by genedan** [casact/chainladder-python#446]
**Describe the bug**
I think the latest version of scipy (1.11.1) is causing an issue in the TailClark calculation. Running the documentation example raises an exception which gets remedied if I downgrade to 1.10.1.

**To Reproduce**
```python
import chainladder as cl

genins = cl.load_sample('genins')
dev = cl.ClarkLDF()
tail = cl.TailClark()
tail.fit(dev.fit_transform(genins)).ldf_
```

Raises the exception:

```python
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.8109.197/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 6, in <module>
  File "/home/ubuntu/chainladder-python/venv/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/ubuntu/chainladder-python/venv/lib/python3.10/site-packages/sklearn/base.py", line 915, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/ubuntu/chainladder-python/chainladder/development/clark.py", line 187, in fit
    minimize(fun=solver, x0=x0, bounds=bounds).x.reshape(1, 1, 1, -1)
  File "/home/ubuntu/chainladder-python/venv/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 533, in minimize
    raise ValueError("'x0' must only have one dimension.")
ValueError: 'x0' must only have one dimension.
```

**Expected behavior**
```python
tail.fit(dev.fit_transform(genins)).ldf_
          12-24     24-36     36-48     48-60    60-72    72-84     84-96   96-108   108-120   120-132   132-144
(All)  4.095043  1.720477  1.342451  1.200514  1.13061  1.09101  1.066509  1.05038  1.039255  1.031295  1.253996
```

**Desktop (please complete the following information):**
 - Numpy 1.24.4
 - Pandas 2.0.3
 - SciPy 1.11.1
 - Chainladder latest (1c0a3251526cf1dbc5a176794984eb7169575fce)

**Comment by jbogaardt** [comment]
Released in v0.8.18
