### ISSUE TITLE
Empty triangle cannot be printed [BUG]

### ISSUE THREAD

**Issue by MatthewCaseres** [casact/chainladder-python#491]
**Describe the bug**
I cannot print an empty triangle.

**To Reproduce**
```python
import chainladder as cl
print(cl.Triangle())
```

error is
```
>>> print(cl.Triangle()
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matthewcaseres/Documents/GitHub/chainladder-python/chainladder/core/display.py", line 16, in __repr__
    if (self.values.shape[0], self.values.shape[1]) == (1, 1):
```

**Expected behavior**
The empty triangle should print

**Comment by kennethshsu** [comment]
Now this

```python
import chainladder as cl
empty_tri = cl.Triangle()
empty_tri
```

Returns `Triangle is empty.`.
