### ISSUE TITLE
Can't set valuation attribute_

### ISSUE THREAD

**Issue by pdavidson-actuary** [casact/chainladder-python#88]
With version 0.7.3 I get this error when initialising a triangle. 
Eliminated numpy (running numpy 1.19.0 but also same issue with numpy 1.16.4).

> cl.load_sample('raa')
> Traceback (most recent call last):
>   File "C:\Program Files\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-5-fb7555d41c5d>", line 1, in <module>
>     cl.load_sample('raa')
>   File "G:\My Drive\PyCharm\chainladder-python\chainladder\utils\utility_functions.py", line 51, in load_sample
>     return Triangle(df, origin=origin, development=development, index=index,
>   File "G:\My Drive\PyCharm\chainladder-python\chainladder\core\base.py", line 111, in __init__
>     self.valuation = self._valuation_triangle()
> AttributeError: can't set attribute

**Comment by pdavidson-actuary** [comment]
I think this is because valuation is defined as a property in Triangle but an attribute in TriangleBase.

**Comment by pdavidson-actuary** [comment]
issue with git.
